Add customer name and timestamp to report name.
Particular/Particular.EndpointThroughputCounter pull request #14
Opened 2022-10-07 18:50 UTC by awright18

Adds customer name to the report name, and confirms running when reports are found in the working directory.

2022-10-10 13:11 UTC, DavidBoike requested changes

2022-10-10 13:11 UTC, DavidBoike commented on src/Tool/Commands/BaseCommand.cs
> +            $"{customerName}-{reportName}");
Guard against illegal filename chars
```suggestion
        var customerFileName = Regex.Replace(customerName, @"[^\w\d]+", "-").Trim('-').ToLower()  
        var outputPath = Path.Join(Environment.CurrentDirectory,
            $"{customerFileName-{reportName}");
```

2022-10-10 20:54 UTC, awright18 commented on src/Tool/Commands/BaseCommand.cs
> +    bool ConfirmCreateNewReport()
This isn't looking for the same file, just any customer throughput file in the working directory. If you don't think that is necessary, then I'm happy to eliminate any code that cares about that.

2022-10-11 13:36 UTC, DavidBoike commented on src/Tool/Commands/BaseCommand.cs
> +    bool ConfirmCreateNewReport()
Yeah let's kill it in the name of simplicity. The files we create after this PR will be nice and sortable so they can grab the most recent one.

2022-10-11 13:45 UTC, awright18 commented on src/Tool/Commands/BaseCommand.cs
> +    bool ConfirmCreateNewReport()
Removed

2022-10-11 14:37 UTC, DavidBoike commented on src/Tool/Commands/BaseCommand.cs
> +            $"{customerFileName}-{reportName}-{GenerateReportTimeStamp(DateTime.Now)}");
Still need this - for example `dateTime.Day` won't produce leading zero and the result would not be sortable.
```suggestion
            $"{customerFileName}-{reportName}-{DateTime.Now:yyyyMMdd-HHmmss}");
```

2022-10-11 14:37 UTC, DavidBoike commented on src/Tool/Commands/BaseCommand.cs
Remove this method, see below.
```suggestion
```

2022-10-11 15:07 UTC, DavidBoike approved these changes

2022-10-11 15:07 UTC, merged